version: '3.8'
services:

  frontend:
    build:
      context: ../../frontend
      dockerfile: ./.deploy/develop/Dockerfile
    command: npm run serve -- --port 80
    stdin_open: true
    tty: true
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - ../../frontend/src:/vue-ui/src

  backend:
    environment:
      - APP_DEBUG=true

  adminer:
    image: adminer:4.8.1
    container_name: ${PROJECT_NAME:-template}-adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT:-8080}:8080
    depends_on:
      - db